### ISSUE TITLE
Create a requirement.txt file

### ISSUE THREAD

**Issue by sebastianhritcu** [parthk3004/Quizzaro#1]
Hello,

I think it is easy to have a requirements.txt file to test your project in a virtual environment. Content of my requirements.txt looks something like this:
Flask=1.1.1
Flask-CLI=0.4.0
pandas=0.25.3
matplotlib=3.1.2
pygal=2.4.0
xlrd=1.2.0

Could you please confirm if your project works and if the requirements suggested are correct or need to be changed?

Thanks,
Sebastian

**Comment by parthk3004** [comment]
yes it works you can try now using python and response file from main folder
